### ISSUE TITLE
Does 2.0.1 require PHPUnit ^9? 

### ISSUE THREAD

**Issue by countless-integers** [Codeception/module-asserts#27]
I started getting errors after this upgrade, i.e.

```
[Error] Call to undefined method Codeception\PHPUnit\TestCase::assertMatchesRegularExpression() 
```

going down the rabbit hole, it seems like this is going through the phpunit wrapper to a method in phpunit with the same name, but `assertMatchesRegularExpression` wasn't present in phpunit ^8. Trying to force phpunit to 9.5 results in:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires phpunit/phpunit ^9.5, found phpunit/phpunit[9.5.0, ..., 9.5.x-dev] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - codeception/phpunit-wrapper 8.1.6 requires phpunit/phpunit ^8.0 -> found phpunit/phpunit[8.0.0, ..., 8.5.x-dev] but it conflicts with your root composer.json require (^9.5).
    - codeception/codeception 4.2.2 requires codeception/phpunit-wrapper >6.0.15 <6.1.0 | ^6.6.1 | ^7.7.1 | ^8.1.1 | ^9.0 -> satisfiable by codeception/phpunit-wrapper[8.1.6].
    - codeception/codeception is locked to version 4.2.2 and an update of this package was not requested.
```

Am I missing something here?

Using codeception 4.2.2, php 8.0, phpunit 8.5.30, lib-asserts 1.13.2, module-asserts 1.3.1

**Comment by Naktibalda** [comment]
You have to upgrade `codeception/phpunit-wrapper` to `^9` too.

**Comment by Naktibalda** [comment]
You can use `assertRegExp` with older versions of PHPUnit.

**Comment by countless-integers** [comment]
I think `assertRegExp` uses the same `assertMatchesRegularExpression` from the wrapper. In any case, upgrading the wrapper solves it for me without any extra changes and any tests failing. Thanks!
